<style>
	#nette-debug .nette-elasticSearchPanel,
	#tracy-debug .nette-elasticSearchPanel { min-width: 700px; }
	#nette-debug .nette-elasticSearchPanel h2,
	#tracy-debug .nette-elasticSearchPanel h2 { font-size: 22px; font-weight: bold; }
	#nette-debug .nette-elasticSearchPanel small,
	#tracy-debug .nette-elasticSearchPanel small { font-size: 70%; font-weight: normal; }
	#nette-debug .nette-elasticSearchPanel code,
	#tracy-debug .nette-elasticSearchPanel code { font-size: 100%; font-weight: inherit; }
	#nette-debug .nette-elasticSearchPanel table,
	#tracy-debug .nette-elasticSearchPanel table { width: 100%; }
	#nette-debug .nette-elasticSearchPanel table th,
	#tracy-debug .nette-elasticSearchPanel table th { text-align: right; }
</style>

<?php foreach ($processedQueries as $host => $queries): ?>
	<h1 class="nette-elasticSearchPanel"><code><?php echo $esc($host) ?></code> - Queries: <?php echo $esc(count($queries)); ?>, time: <?php echo $esc($totalTime); ?> </h1>
	<div class="nette-inner tracy-inner nette-elasticSearchPanel">
		<?php foreach($queries as $query): ?>
			<?php /* \Tracy\Debugger::dump($query); */ ?>

			<?php $request = $query->body; ?>
			<?php $response = $query->response; ?>
			<?php $time = $query->duration; ?>
			<h2>
				<code><?php echo $esc($query->fullURI); ?></code>
				<small><?php echo $esc(number_format($time * 1000, 2)); ?>ms</small>
			</h2>

			<table>
				<?php if ($request) { $requestData = $extractData($request); ?><tr>
					<th width="70">Request:</th>
					<td><?php echo $click($requestData, TRUE, 15); ?></td>
					</tr><?php } ?>

				<?php if ($response) { $responseData = $extractData($response); ?>
					<?php if (stripos($query->fullURI, '_search') !== FALSE) { ?>
						<?php if (isset($responseData['took'])) { ?><tr>
							<th width="70">Took:</th><td><?php echo $click($responseData['took']); ?></td>
							</tr><?php } ?>

						<?php if (isset($responseData['timed_out']) && $responseData['timed_out']) { ?><tr>
							<th width="70">Timed&nbsp;out:</th><td>yes</td>
						</tr><?php } ?>

						<?php if (isset($responseData['_shards'])) { ?><tr>
							<th width="70">Shards:</th><td>
								total: <?php echo $esc($responseData['_shards']['total']); ?>,
								successful: <?php echo $esc($responseData['_shards']['successful']); ?>,
								failed: <?php echo $esc($responseData['_shards']['failed']); ?>
							</td>
							</tr><?php } ?>

						<?php if (isset($responseData['hits'])) { ?>
							<tr><th width="70">Total&nbsp;hits:</th><td><?php echo $click($responseData['hits']['total']); ?></td></tr>
							<tr><th width="70">Max&nbsp;hit&nbsp;score:</th><td><?php echo $click($responseData['hits']['max_score']); ?></td></tr>
							<tr><th width="70">Results:</th><td><?php echo $click($responseData['hits']['hits'], TRUE, 15); ?></td></tr>
							<?php if (isset($responseData['aggregations'])) { ?>
								<tr><th width="70">Aggregation:</th><td><?php echo $click($responseData['aggregations'], TRUE, 15); ?></td></tr>
							<?php } ?>
						<?php } ?>

					<?php } else { ?>
						<tr>
							<th width="70">Response:</th>
							<td><?php echo $click($extractData($response), TRUE, 15); ?></td>
						</tr>
					<?php } ?>

					<?php if(isset($query->explain)) { ?>
						<tr>
							<th width="70">Explain:</th>
							<?php /* \Tracy\Debugger::dump($query); */ ?>
							<td><?php echo $click($query->explain, TRUE, 15); ?></td>
						</tr>
					<?php } ?>

				<?php } elseif (isset($query->exception)) { ?>
					<tr>
						<th width="70">Error:</th>
						<td style="color:red"><?php echo $esc($query->exception); ?></td>
					</tr>
				<?php } ?>

			</table>
		<?php endforeach; ?>
	</div>
<?php endforeach; ?>
