<style>
	#nette-debug .nette-elasticSearchPanel,
	#tracy-debug .nette-elasticSearchPanel {
		min-width: 700px;
	}

	#nette-debug .nette-elasticSearchPanel h2,
	#tracy-debug .nette-elasticSearchPanel h2 {
		font-size: 22px;
		font-weight: bold;
	}

	#nette-debug .nette-elasticSearchPanel small,
	#tracy-debug .nette-elasticSearchPanel small {
		font-size: 70%;
		font-weight: normal;
	}

	#nette-debug .nette-elasticSearchPanel code,
	#tracy-debug .nette-elasticSearchPanel code {
		font-size: 100%;
		font-weight: inherit;
	}

	#nette-debug .nette-elasticSearchPanel table,
	#tracy-debug .nette-elasticSearchPanel table {
		width: 100%;
	}

	#nette-debug .nette-elasticSearchPanel table th,
	#tracy-debug .nette-elasticSearchPanel table th {
		text-align: right;
	}
</style>

<?php foreach ($processedQueries as $host => $queries): ?>
	<h1 class="nette-elasticSearchPanel"><code><?php echo $esc($host) ?></code> -
		Queries: <?php echo $esc(count($queries)/3); ?>, time: <?php echo $esc($totalTime); ?> </h1>
	<div class="nette-inner tracy-inner nette-elasticSearchPanel">
		<?php foreach ($queries as $query): ?>
			<?php /* \Tracy\Debugger::dump($query); */ ?>

			<?php $query = \Nette\Utils\ArrayHash::from($query); ?>
			<h2>
				<?php echo $esc($query->message) ?>
			</h2>

			<table>
				<?php foreach ($query as $key => $val) {
					if ($key == "message") {
						continue;
					} ?>
					<tr>
						<th width="70"><?php echo ucfirst($key) ?>:</th>
						<td><?php echo $click($val); ?></td>
					</tr>
				<?php } ?>

			</table>
		<?php endforeach; ?>
	</div>
<?php endforeach; ?>
